// Code generated by ent, DO NOT EDIT.

package errorcode

const (
	// Label holds the string label denoting the errorcode type in the database.
	Label = "error_code"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldGrpcStatus holds the string denoting the grpc_status field in the database.
	FieldGrpcStatus = "grpc_status"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// Table holds the table name of the errorcode in the database.
	Table = "error_codes"
)

// Columns holds all SQL columns for errorcode fields.
var Columns = []string{
	FieldID,
	FieldErrorCode,
	FieldGrpcStatus,
	FieldName,
	FieldMessage,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
