// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Yostardev/errors/store/ent/errorcode"
	"github.com/Yostardev/errors/store/ent/predicate"
)

// ErrorCodeDelete is the builder for deleting a ErrorCode entity.
type ErrorCodeDelete struct {
	config
	hooks    []Hook
	mutation *ErrorCodeMutation
}

// Where appends a list predicates to the ErrorCodeDelete builder.
func (ecd *ErrorCodeDelete) Where(ps ...predicate.ErrorCode) *ErrorCodeDelete {
	ecd.mutation.Where(ps...)
	return ecd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ecd *ErrorCodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, ErrorCodeMutation](ctx, ecd.sqlExec, ecd.mutation, ecd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ecd *ErrorCodeDelete) ExecX(ctx context.Context) int {
	n, err := ecd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ecd *ErrorCodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(errorcode.Table, sqlgraph.NewFieldSpec(errorcode.FieldID, field.TypeInt))
	if ps := ecd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ecd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ecd.mutation.done = true
	return affected, err
}

// ErrorCodeDeleteOne is the builder for deleting a single ErrorCode entity.
type ErrorCodeDeleteOne struct {
	ecd *ErrorCodeDelete
}

// Where appends a list predicates to the ErrorCodeDelete builder.
func (ecdo *ErrorCodeDeleteOne) Where(ps ...predicate.ErrorCode) *ErrorCodeDeleteOne {
	ecdo.ecd.mutation.Where(ps...)
	return ecdo
}

// Exec executes the deletion query.
func (ecdo *ErrorCodeDeleteOne) Exec(ctx context.Context) error {
	n, err := ecdo.ecd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{errorcode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ecdo *ErrorCodeDeleteOne) ExecX(ctx context.Context) {
	if err := ecdo.Exec(ctx); err != nil {
		panic(err)
	}
}
