// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Yostardev/errors/store/ent/errorcode"
	"github.com/Yostardev/errors/store/ent/predicate"
)

// ErrorCodeUpdate is the builder for updating ErrorCode entities.
type ErrorCodeUpdate struct {
	config
	hooks    []Hook
	mutation *ErrorCodeMutation
}

// Where appends a list predicates to the ErrorCodeUpdate builder.
func (ecu *ErrorCodeUpdate) Where(ps ...predicate.ErrorCode) *ErrorCodeUpdate {
	ecu.mutation.Where(ps...)
	return ecu
}

// SetErrorCode sets the "error_code" field.
func (ecu *ErrorCodeUpdate) SetErrorCode(i int) *ErrorCodeUpdate {
	ecu.mutation.ResetErrorCode()
	ecu.mutation.SetErrorCode(i)
	return ecu
}

// AddErrorCode adds i to the "error_code" field.
func (ecu *ErrorCodeUpdate) AddErrorCode(i int) *ErrorCodeUpdate {
	ecu.mutation.AddErrorCode(i)
	return ecu
}

// SetGrpcStatus sets the "grpc_status" field.
func (ecu *ErrorCodeUpdate) SetGrpcStatus(u uint32) *ErrorCodeUpdate {
	ecu.mutation.ResetGrpcStatus()
	ecu.mutation.SetGrpcStatus(u)
	return ecu
}

// AddGrpcStatus adds u to the "grpc_status" field.
func (ecu *ErrorCodeUpdate) AddGrpcStatus(u int32) *ErrorCodeUpdate {
	ecu.mutation.AddGrpcStatus(u)
	return ecu
}

// SetName sets the "name" field.
func (ecu *ErrorCodeUpdate) SetName(s string) *ErrorCodeUpdate {
	ecu.mutation.SetName(s)
	return ecu
}

// SetMessage sets the "message" field.
func (ecu *ErrorCodeUpdate) SetMessage(s string) *ErrorCodeUpdate {
	ecu.mutation.SetMessage(s)
	return ecu
}

// Mutation returns the ErrorCodeMutation object of the builder.
func (ecu *ErrorCodeUpdate) Mutation() *ErrorCodeMutation {
	return ecu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ecu *ErrorCodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, ErrorCodeMutation](ctx, ecu.sqlSave, ecu.mutation, ecu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ecu *ErrorCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := ecu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ecu *ErrorCodeUpdate) Exec(ctx context.Context) error {
	_, err := ecu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecu *ErrorCodeUpdate) ExecX(ctx context.Context) {
	if err := ecu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ecu *ErrorCodeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(errorcode.Table, errorcode.Columns, sqlgraph.NewFieldSpec(errorcode.FieldID, field.TypeInt))
	if ps := ecu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ecu.mutation.ErrorCode(); ok {
		_spec.SetField(errorcode.FieldErrorCode, field.TypeInt, value)
	}
	if value, ok := ecu.mutation.AddedErrorCode(); ok {
		_spec.AddField(errorcode.FieldErrorCode, field.TypeInt, value)
	}
	if value, ok := ecu.mutation.GrpcStatus(); ok {
		_spec.SetField(errorcode.FieldGrpcStatus, field.TypeUint32, value)
	}
	if value, ok := ecu.mutation.AddedGrpcStatus(); ok {
		_spec.AddField(errorcode.FieldGrpcStatus, field.TypeUint32, value)
	}
	if value, ok := ecu.mutation.Name(); ok {
		_spec.SetField(errorcode.FieldName, field.TypeString, value)
	}
	if value, ok := ecu.mutation.Message(); ok {
		_spec.SetField(errorcode.FieldMessage, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ecu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{errorcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ecu.mutation.done = true
	return n, nil
}

// ErrorCodeUpdateOne is the builder for updating a single ErrorCode entity.
type ErrorCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ErrorCodeMutation
}

// SetErrorCode sets the "error_code" field.
func (ecuo *ErrorCodeUpdateOne) SetErrorCode(i int) *ErrorCodeUpdateOne {
	ecuo.mutation.ResetErrorCode()
	ecuo.mutation.SetErrorCode(i)
	return ecuo
}

// AddErrorCode adds i to the "error_code" field.
func (ecuo *ErrorCodeUpdateOne) AddErrorCode(i int) *ErrorCodeUpdateOne {
	ecuo.mutation.AddErrorCode(i)
	return ecuo
}

// SetGrpcStatus sets the "grpc_status" field.
func (ecuo *ErrorCodeUpdateOne) SetGrpcStatus(u uint32) *ErrorCodeUpdateOne {
	ecuo.mutation.ResetGrpcStatus()
	ecuo.mutation.SetGrpcStatus(u)
	return ecuo
}

// AddGrpcStatus adds u to the "grpc_status" field.
func (ecuo *ErrorCodeUpdateOne) AddGrpcStatus(u int32) *ErrorCodeUpdateOne {
	ecuo.mutation.AddGrpcStatus(u)
	return ecuo
}

// SetName sets the "name" field.
func (ecuo *ErrorCodeUpdateOne) SetName(s string) *ErrorCodeUpdateOne {
	ecuo.mutation.SetName(s)
	return ecuo
}

// SetMessage sets the "message" field.
func (ecuo *ErrorCodeUpdateOne) SetMessage(s string) *ErrorCodeUpdateOne {
	ecuo.mutation.SetMessage(s)
	return ecuo
}

// Mutation returns the ErrorCodeMutation object of the builder.
func (ecuo *ErrorCodeUpdateOne) Mutation() *ErrorCodeMutation {
	return ecuo.mutation
}

// Where appends a list predicates to the ErrorCodeUpdate builder.
func (ecuo *ErrorCodeUpdateOne) Where(ps ...predicate.ErrorCode) *ErrorCodeUpdateOne {
	ecuo.mutation.Where(ps...)
	return ecuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ecuo *ErrorCodeUpdateOne) Select(field string, fields ...string) *ErrorCodeUpdateOne {
	ecuo.fields = append([]string{field}, fields...)
	return ecuo
}

// Save executes the query and returns the updated ErrorCode entity.
func (ecuo *ErrorCodeUpdateOne) Save(ctx context.Context) (*ErrorCode, error) {
	return withHooks[*ErrorCode, ErrorCodeMutation](ctx, ecuo.sqlSave, ecuo.mutation, ecuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ecuo *ErrorCodeUpdateOne) SaveX(ctx context.Context) *ErrorCode {
	node, err := ecuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ecuo *ErrorCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := ecuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecuo *ErrorCodeUpdateOne) ExecX(ctx context.Context) {
	if err := ecuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ecuo *ErrorCodeUpdateOne) sqlSave(ctx context.Context) (_node *ErrorCode, err error) {
	_spec := sqlgraph.NewUpdateSpec(errorcode.Table, errorcode.Columns, sqlgraph.NewFieldSpec(errorcode.FieldID, field.TypeInt))
	id, ok := ecuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ErrorCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ecuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, errorcode.FieldID)
		for _, f := range fields {
			if !errorcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != errorcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ecuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ecuo.mutation.ErrorCode(); ok {
		_spec.SetField(errorcode.FieldErrorCode, field.TypeInt, value)
	}
	if value, ok := ecuo.mutation.AddedErrorCode(); ok {
		_spec.AddField(errorcode.FieldErrorCode, field.TypeInt, value)
	}
	if value, ok := ecuo.mutation.GrpcStatus(); ok {
		_spec.SetField(errorcode.FieldGrpcStatus, field.TypeUint32, value)
	}
	if value, ok := ecuo.mutation.AddedGrpcStatus(); ok {
		_spec.AddField(errorcode.FieldGrpcStatus, field.TypeUint32, value)
	}
	if value, ok := ecuo.mutation.Name(); ok {
		_spec.SetField(errorcode.FieldName, field.TypeString, value)
	}
	if value, ok := ecuo.mutation.Message(); ok {
		_spec.SetField(errorcode.FieldMessage, field.TypeString, value)
	}
	_node = &ErrorCode{config: ecuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ecuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{errorcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ecuo.mutation.done = true
	return _node, nil
}
