// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Yostardev/errors/store/ent/errorcode"
	"github.com/Yostardev/errors/store/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeErrorCode = "ErrorCode"
)

// ErrorCodeMutation represents an operation that mutates the ErrorCode nodes in the graph.
type ErrorCodeMutation struct {
	config
	op             Op
	typ            string
	id             *int
	error_code     *int
	adderror_code  *int
	grpc_status    *uint32
	addgrpc_status *int32
	name           *string
	message        *string
	clearedFields  map[string]struct{}
	done           bool
	oldValue       func(context.Context) (*ErrorCode, error)
	predicates     []predicate.ErrorCode
}

var _ ent.Mutation = (*ErrorCodeMutation)(nil)

// errorcodeOption allows management of the mutation configuration using functional options.
type errorcodeOption func(*ErrorCodeMutation)

// newErrorCodeMutation creates new mutation for the ErrorCode entity.
func newErrorCodeMutation(c config, op Op, opts ...errorcodeOption) *ErrorCodeMutation {
	m := &ErrorCodeMutation{
		config:        c,
		op:            op,
		typ:           TypeErrorCode,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withErrorCodeID sets the ID field of the mutation.
func withErrorCodeID(id int) errorcodeOption {
	return func(m *ErrorCodeMutation) {
		var (
			err   error
			once  sync.Once
			value *ErrorCode
		)
		m.oldValue = func(ctx context.Context) (*ErrorCode, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ErrorCode.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withErrorCode sets the old ErrorCode of the mutation.
func withErrorCode(node *ErrorCode) errorcodeOption {
	return func(m *ErrorCodeMutation) {
		m.oldValue = func(context.Context) (*ErrorCode, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ErrorCodeMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ErrorCodeMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ErrorCodeMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ErrorCodeMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ErrorCode.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetErrorCode sets the "error_code" field.
func (m *ErrorCodeMutation) SetErrorCode(i int) {
	m.error_code = &i
	m.adderror_code = nil
}

// ErrorCode returns the value of the "error_code" field in the mutation.
func (m *ErrorCodeMutation) ErrorCode() (r int, exists bool) {
	v := m.error_code
	if v == nil {
		return
	}
	return *v, true
}

// OldErrorCode returns the old "error_code" field's value of the ErrorCode entity.
// If the ErrorCode object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ErrorCodeMutation) OldErrorCode(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldErrorCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldErrorCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldErrorCode: %w", err)
	}
	return oldValue.ErrorCode, nil
}

// AddErrorCode adds i to the "error_code" field.
func (m *ErrorCodeMutation) AddErrorCode(i int) {
	if m.adderror_code != nil {
		*m.adderror_code += i
	} else {
		m.adderror_code = &i
	}
}

// AddedErrorCode returns the value that was added to the "error_code" field in this mutation.
func (m *ErrorCodeMutation) AddedErrorCode() (r int, exists bool) {
	v := m.adderror_code
	if v == nil {
		return
	}
	return *v, true
}

// ResetErrorCode resets all changes to the "error_code" field.
func (m *ErrorCodeMutation) ResetErrorCode() {
	m.error_code = nil
	m.adderror_code = nil
}

// SetGrpcStatus sets the "grpc_status" field.
func (m *ErrorCodeMutation) SetGrpcStatus(u uint32) {
	m.grpc_status = &u
	m.addgrpc_status = nil
}

// GrpcStatus returns the value of the "grpc_status" field in the mutation.
func (m *ErrorCodeMutation) GrpcStatus() (r uint32, exists bool) {
	v := m.grpc_status
	if v == nil {
		return
	}
	return *v, true
}

// OldGrpcStatus returns the old "grpc_status" field's value of the ErrorCode entity.
// If the ErrorCode object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ErrorCodeMutation) OldGrpcStatus(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGrpcStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGrpcStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGrpcStatus: %w", err)
	}
	return oldValue.GrpcStatus, nil
}

// AddGrpcStatus adds u to the "grpc_status" field.
func (m *ErrorCodeMutation) AddGrpcStatus(u int32) {
	if m.addgrpc_status != nil {
		*m.addgrpc_status += u
	} else {
		m.addgrpc_status = &u
	}
}

// AddedGrpcStatus returns the value that was added to the "grpc_status" field in this mutation.
func (m *ErrorCodeMutation) AddedGrpcStatus() (r int32, exists bool) {
	v := m.addgrpc_status
	if v == nil {
		return
	}
	return *v, true
}

// ResetGrpcStatus resets all changes to the "grpc_status" field.
func (m *ErrorCodeMutation) ResetGrpcStatus() {
	m.grpc_status = nil
	m.addgrpc_status = nil
}

// SetName sets the "name" field.
func (m *ErrorCodeMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ErrorCodeMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the ErrorCode entity.
// If the ErrorCode object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ErrorCodeMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *ErrorCodeMutation) ResetName() {
	m.name = nil
}

// SetMessage sets the "message" field.
func (m *ErrorCodeMutation) SetMessage(s string) {
	m.message = &s
}

// Message returns the value of the "message" field in the mutation.
func (m *ErrorCodeMutation) Message() (r string, exists bool) {
	v := m.message
	if v == nil {
		return
	}
	return *v, true
}

// OldMessage returns the old "message" field's value of the ErrorCode entity.
// If the ErrorCode object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ErrorCodeMutation) OldMessage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMessage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMessage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMessage: %w", err)
	}
	return oldValue.Message, nil
}

// ResetMessage resets all changes to the "message" field.
func (m *ErrorCodeMutation) ResetMessage() {
	m.message = nil
}

// Where appends a list predicates to the ErrorCodeMutation builder.
func (m *ErrorCodeMutation) Where(ps ...predicate.ErrorCode) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ErrorCodeMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ErrorCodeMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.ErrorCode, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ErrorCodeMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ErrorCodeMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (ErrorCode).
func (m *ErrorCodeMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ErrorCodeMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.error_code != nil {
		fields = append(fields, errorcode.FieldErrorCode)
	}
	if m.grpc_status != nil {
		fields = append(fields, errorcode.FieldGrpcStatus)
	}
	if m.name != nil {
		fields = append(fields, errorcode.FieldName)
	}
	if m.message != nil {
		fields = append(fields, errorcode.FieldMessage)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ErrorCodeMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case errorcode.FieldErrorCode:
		return m.ErrorCode()
	case errorcode.FieldGrpcStatus:
		return m.GrpcStatus()
	case errorcode.FieldName:
		return m.Name()
	case errorcode.FieldMessage:
		return m.Message()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ErrorCodeMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case errorcode.FieldErrorCode:
		return m.OldErrorCode(ctx)
	case errorcode.FieldGrpcStatus:
		return m.OldGrpcStatus(ctx)
	case errorcode.FieldName:
		return m.OldName(ctx)
	case errorcode.FieldMessage:
		return m.OldMessage(ctx)
	}
	return nil, fmt.Errorf("unknown ErrorCode field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ErrorCodeMutation) SetField(name string, value ent.Value) error {
	switch name {
	case errorcode.FieldErrorCode:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetErrorCode(v)
		return nil
	case errorcode.FieldGrpcStatus:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGrpcStatus(v)
		return nil
	case errorcode.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case errorcode.FieldMessage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMessage(v)
		return nil
	}
	return fmt.Errorf("unknown ErrorCode field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ErrorCodeMutation) AddedFields() []string {
	var fields []string
	if m.adderror_code != nil {
		fields = append(fields, errorcode.FieldErrorCode)
	}
	if m.addgrpc_status != nil {
		fields = append(fields, errorcode.FieldGrpcStatus)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ErrorCodeMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case errorcode.FieldErrorCode:
		return m.AddedErrorCode()
	case errorcode.FieldGrpcStatus:
		return m.AddedGrpcStatus()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ErrorCodeMutation) AddField(name string, value ent.Value) error {
	switch name {
	case errorcode.FieldErrorCode:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddErrorCode(v)
		return nil
	case errorcode.FieldGrpcStatus:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddGrpcStatus(v)
		return nil
	}
	return fmt.Errorf("unknown ErrorCode numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ErrorCodeMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ErrorCodeMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ErrorCodeMutation) ClearField(name string) error {
	return fmt.Errorf("unknown ErrorCode nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ErrorCodeMutation) ResetField(name string) error {
	switch name {
	case errorcode.FieldErrorCode:
		m.ResetErrorCode()
		return nil
	case errorcode.FieldGrpcStatus:
		m.ResetGrpcStatus()
		return nil
	case errorcode.FieldName:
		m.ResetName()
		return nil
	case errorcode.FieldMessage:
		m.ResetMessage()
		return nil
	}
	return fmt.Errorf("unknown ErrorCode field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ErrorCodeMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ErrorCodeMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ErrorCodeMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ErrorCodeMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ErrorCodeMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ErrorCodeMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ErrorCodeMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ErrorCode unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ErrorCodeMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ErrorCode edge %s", name)
}
