// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Yostardev/errors/store/ent/errorcode"
	"github.com/Yostardev/errors/store/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	errorcodeMixin := schema.ErrorCode{}.Mixin()
	errorcodeMixinFields0 := errorcodeMixin[0].Fields()
	_ = errorcodeMixinFields0
	errorcodeFields := schema.ErrorCode{}.Fields()
	_ = errorcodeFields
	// errorcodeDescCreatedAt is the schema descriptor for created_at field.
	errorcodeDescCreatedAt := errorcodeMixinFields0[1].Descriptor()
	// errorcode.DefaultCreatedAt holds the default value on creation for the created_at field.
	errorcode.DefaultCreatedAt = errorcodeDescCreatedAt.Default.(func() time.Time)
	// errorcodeDescUpdatedAt is the schema descriptor for updated_at field.
	errorcodeDescUpdatedAt := errorcodeMixinFields0[2].Descriptor()
	// errorcode.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	errorcode.DefaultUpdatedAt = errorcodeDescUpdatedAt.Default.(func() time.Time)
	// errorcode.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	errorcode.UpdateDefaultUpdatedAt = errorcodeDescUpdatedAt.UpdateDefault.(func() time.Time)
}
