// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ErrorCodesColumns holds the columns for the "error_codes" table.
	ErrorCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "error_code", Type: field.TypeInt, Unique: true},
		{Name: "grpc_status", Type: field.TypeUint32},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "message", Type: field.TypeString},
	}
	// ErrorCodesTable holds the schema information for the "error_codes" table.
	ErrorCodesTable = &schema.Table{
		Name:       "error_codes",
		Columns:    ErrorCodesColumns,
		PrimaryKey: []*schema.Column{ErrorCodesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ErrorCodesTable,
	}
)

func init() {
}
